# Generated by Django 5.2.4 on 2025-08-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('heart_rate', 'Heart Rate'), ('weight', 'Weight'), ('height', 'Height'), ('temperature', 'Temperature'), ('blood_sugar', 'Blood Sugar'), ('cholesterol', 'Cholesterol'), ('oxygen_saturation', 'Oxygen Saturation')], max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='patients.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.PositiveIntegerField(help_text='Systolic Blood Pressure')),
                ('diastolic_bp', models.PositiveIntegerField(help_text='Diastolic Blood Pressure')),
                ('heart_rate', models.PositiveIntegerField(help_text='Heart Rate (BPM)')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Temperature in Celsius', max_digits=4)),
                ('respiratory_rate', models.PositiveIntegerField(help_text='Respiratory Rate (per minute)')),
                ('oxygen_saturation', models.PositiveIntegerField(help_text='Oxygen Saturation (%)')),
                ('recorded_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]